### ISSUE TITLE
How to upload package to specific Package flight

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/msstore-cli#22]
Is possible upload package into specific Package flight with CLI? And if so, how? Currently I distribute Dev version of my app via this Package flight and would be really interesting to have option to do releases by this way.

**Comment by azchohfi** [comment]
We currently don't support flights, but it is something we want to support. I just pushed a small support for listing flights and some other smaller commands related to flighting.
Could you detail your scenario a little bit more? Which command do you expect that should support flighting? The publish command? And for what type of app is this for?

**Comment by MatthewSteeples** [comment]
From our perspective the main thing we'd like is to be able to publish packages (and monitor the publish process) of a particular flight.

We have an `Insiders` flight that is used internally and with some external customers that our CI pipeline deploys to. It's a win32 app packaged as a store app by Visual Studio, so we have an msix / msixbundle that we'd want to upload.

**Comment by JanRajnoha** [comment]
Yeah, same scenario. I have in flight some insiders who are testing my app, but currently I have to manually download artifact, upload it to center and confirm. It is not so time consuming I could not do it every day :) but it is last piece to fully automate CI.

And app is WinAppSDK app and publish command seems legit for this task with some optional parameter specifying it is package flight.

**Comment by azchohfi** [comment]
We still don't support rollout, but we should support it soon.
