### ISSUE TITLE
Seller ID?

### ISSUE THREAD

**Issue by AnalogJ** [microsoft/msstore-cli#26]
I'm having trouble finding my seller id to reconfigure the CLI. 

I was able to find the Tenant ID, Client ID and Client Secret using this url: https://learn.microsoft.com/en-us/windows/apps/publish/partner-center/manage-azure-ad-applications-in-partner-center#create-a-new-azure-ad-application-account-in-your-organizations-directory-and-add-it-to-your-partner-center-account

However there's nothing there about the Seller ID.

**Comment by azchohfi** [comment]
It should be on this website:
https://partner.microsoft.com/en-us/dashboard/account/v3/organization/legalinfo#developer
![image](https://github.com/microsoft/msstore-cli/assets/527713/4841ea72-40f5-44f3-8788-f3bad3cce0d3)

**Comment by AnalogJ** [comment]
👍  thanks so much!
