### ISSUE TITLE
Error while retrieving Organization.

### ISSUE THREAD

**Issue by tribbloid** [microsoft/msstore-cli#48]
I just want a cli to dump all installed package, then this happens

```
> msstore

  __  __   _                                        __   _       ____    _
 |  \/  | (_)   ___   _ __    ___    ___    ___    / _| | |_    / ___|  | |_    ___    _ __    ___
 | |\/| | | |  / __| | '__|  / _ \  / __|  / _ \  | |_  | __|   \___ \  | __|  / _ \  | '__|  / _ \
 | |  | | | | | (__  | |    | (_) | \__ \ | (_) | |  _| | |_     ___) | | |_  | (_) | | |    |  __/
 |_|  |_| |_|  \___| |_|     \___/  |___/  \___/  |_|    \__|   |____/   \__|  \___/  |_|     \___|

  ____                      ____   _       ___
 |  _ \    ___  __   __    / ___| | |     |_ _|
 | | | |  / _ \ \ \ / /   | |     | |      | |
 | |_| | |  __/  \ V /    | |___  | |___   | |
 |____/   \___|   \_/      \____| |_____| |___|


Use of the Microsoft Store Developer CLI is subject to the terms of the Microsoft Privacy Statement:
https://aka.ms/privacy
You might need to provide some credentials to call the Microsoft Store APIs.
Let's start!

💥 Error while retrieving Organization.
PS C:\Users\pengc> msstore
```

**Comment by azchohfi** [comment]
The Microsoft Store Developer CLI is a tool that helps developers deploy their apps to the Microsoft Store. I believe that what you need is simply the power shell commands like get-appxpackage?

**Comment by Adam-Langley** [comment]
I've got the exact same issue. I'm trying to set up th CLI so I can publish/manage apps.

 - I use msstore cli to reset the configuration
 - the console outputs "retrieving organisation id" it pops up the authenticate browser window.
 - I pick my linked entra account
 - the window disappears immediately and I get the above error

**Comment by ImagineTheGames** [comment]
same issue as above

**Comment by ErraticFox** [comment]
Same issue. It would be kind of nice to get some link with the error that shows how to remedy the error.
